version: "3"
services:
    frontend:
        container_name: react_app
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/app